app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: ${JWT_EXPIRATION}

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  main:
    allow-circular-references: true
  cache:
    type: simple
    cache-names: users, exercises, tickets, messages, training_sessions, training_logs
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;sql.syntax_mys=true
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev
server:
  error:
    include-stacktrace: never
  port: 8081