app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: ${JWT_EXPIRATION}

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  main:
    allow-circular-references: true
  cache:
    type: simple
    cache-names: users, exercises, tickets, messages, training_sessions, training_logs
  datasource:
    url: ${DB_TEST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
  port: 8081
