app:
  jwt:
    secret: secretKey
    expiration-in-ms: 36000000


spring:
  main:
    allow-circular-references: true
  cache:
    type: simple
    cache-names: users, exercises, tickets, messages, training_sessions, training_logs
  datasource:
    url: jdbc:mysql://localhost:3306/gym_tracker
    username: root
    password: xx33xx12
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        show_sql: true

server:
  error:
    include-stacktrace: never


