app:
  jwt:
    secret: secretKey
    expiration-in-ms: 36000000




spring:
  main:
    allow-circular-references: true
  cache:
    type: simple
    cache-names: users, exercises, tickets, messages, training_sessions, training_logs
  datasource:
    url: jdbc:mysql://35.234.173.92:3306/gym_tracker
    username: root
    password: Xx33xx12
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
  port: 20183

